openapi: 3.0.0
info:
  title: Product Service API
  description: API for managing products
  version: "1.0"

servers:
  - url: https://zwzhz3jrej.execute-api.us-east-1.amazonaws.com/prod
    description: Production server

paths:
  /products/{productId}:
    get:
      summary: Get a product by its ID
      operationId: getProductsById
      tags:
        - Product
      parameters:
        - name: productId
          in: path
          required: true
          description: The ID of the product to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /products:
    get:
      summary: Get the list of all products
      operationId: getProductsList
      tags:
        - Product
      responses:
        '200':
          description: An array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - title
        - description
        - price
        - count
      properties:
        id:
          type: string
          description: The product identifier
        title:
          type: string
          description: The name of the product
        description:
          type: string
          description: A short description of the product
        price:
          type: integer
          description: The price of the product
        count:
          type: integer
          description: The available quantity of the product
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description:  error
